BG_IMG_PATH = "./bg_img"
DATA_PATH = "./dataset/export-2021-01-22T07_26_37.465Z.csv"
ORIGINAL_IMG_SAVE_PATH = "./original_template_img"
OUT_PUT_PATH = "./out_put"
MAP_CODE_ELEMENT_LIST = ["headline", "subtitle", "chart_title", "chart_num", "text", "image"]
TEMPLATE_JSON_PATH = "./template_json.json"
FONT_PATH = "./fonts"
FONT_SPACING_PROPORTION = 0.1
# ORGINAL_IMG_SIZE=
